all:
  hosts:
    cisco_device1:
      ansible_host: khoadang  # IP address of the Cisco device
      ansible_user: khoadang        # SSH username
      ansible_password: 1234 # SSH password
      ansible_network_os: ios
      ansible_become: yes
        #ansible_connection: ansible.netcommon.network_cli
      ansible_connection: network_cli
      ansible_become_method: enable
      ansible_become_password: 1234

    cisco_device2:
      ansible_host: khoadang2        
      ansible_user: khoadang2               # SSH username
      ansible_password: 1234       # SSH password
      ansible_network_os: ios
      ansible_become: yes
      ansible_connection: network_cli
      ansible_become_method: enable
      ansible_become_password: 1234

    cisco_device3:
      ansible_host: khoadang1        
      ansible_user: khoadang1               # SSH username
      ansible_password: 1234        # SSH password
      ansible_network_os: ios
      ansible_become: yes
      ansible_connection: network_cli
      ansible_become_method: enable
      ansible_become_password: 1234
